//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class juri
    {
        public string ФИО { get; set; }
        public string пол { get; set; }
        public string почта { get; set; }
        public System.DateTime дата_рождения { get; set; }
        public int страна { get; set; }
        public string телефон { get; set; }
        public string направление { get; set; }
        public string пароль { get; set; }
        public byte[] фото { get; set; }
    }
}
